### ISSUE TITLE
Great repo (and article)

### ISSUE THREAD

**Issue by Xhale1** [0x80/mono-ts#21]
Your [article](https://thijs-koerselman.medium.com/my-quest-for-the-perfect-ts-monorepo-62653d3047eb) was great! I've been searching for my perfect monorepo setup as well. Looking forward to some of the ways you look to adopt TS 5.5 and some of turborepo 2.0's new features.

I'm happy to chat about some ideas if that's something you're interested in!

**Comment by 0x80** [comment]
Hi @Xhale1 thanks for the kind words :) I have been wanting to update the article and repo for a while, but I'm just super busy with multiple active projects. 

But I've already applied some things in my own projects, like turborepo 2 watch mode. And I'm also planning to try RsLib to replace tsup since I think it will simplify things.

In the meantime I also have to maintain isolate-package and the firebase tools clone.

For isolate-package I'm going to try to support the Firebase suggested way of deploying with a single firebase.json file. Which will be challenging probably by should have better support for emulators and simplify things a bit.

So yeah, lots of work to do, so I'm not really looking to have discussions about things ATM, but if you have specific ideas you can always drop them of course.

I have now enabled discussions on this repo, in case you want to use that, so I will close this discussion for now.
