### ISSUE TITLE
Very nice example! Would you mind adding a GAE example too?

### ISSUE THREAD

**Issue by maelp** [0x80/mono-ts#5]
My use-case would be this one:

- having a shared typescript lib between an app / cloud function / an expressjs API server running on Google App Engine
- having the isolate command allowing to package each of those for deployment

**Comment by 0x80** [comment]
I am not planning to add all kinds of different deployments to this example, because the list would become endless. The isolation process is independent of the platform you deploy to. 

I don't currently use GAE so I don't know the details, but once you run `npx isolate` in the package you want to deploy you have a directory that should be no different from any other nodejs application that is not coming from a monorepo. You can a system can install and execute the entry point.

Note that for a web app you probably do not need to run isolate. A platform like nextjs deployed on vercel already supports monorepo setups, as will most other platforms I think.

**Comment by maelp** [comment]
Thanks!
